### ISSUE TITLE
wrong electron-builder on arm64

### ISSUE THREAD

**Issue by bglowney** [apache/cordova-electron#191]
# Bug Report

## Problem

I have a simple cordova app that I have compiled and run as expected on ubuntu18 x86. When I try to repeat the process for ubuntu18 arm64 then the compilation fails. The root cause appears to be that the electron-builder downloaded to the cache is for x86 and cannot be run on arm. I have tried clearing the cache and rerunning and clearing all node modules, platforms, and other build artifacts and reproducing but every time I see the same error in the logs (see below).

### What is expected to happen?

`cordova build electron` successfully outputs a debian artifact

### What does actually happen?

`cordova build electron` fails

## Information

This is my build.json

```
{
  "electron": {
    "linux": {
      "category": "Science",
      "package": ["deb"],
      "arch": [ "arm64" ]
    }
  }
}
```

This is the log output from `cordova build electron`

```
> ~/fooco/fooappf3/fooapp-website/fooapp-cordova$ cordova build electron

  • electron-builder version=20.44.4
  • writing effective config file=platforms/electron/build/builder-effective-config.yaml
  • installing production dependencies platform=linux arch=arm64 appDir=/home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/platforms/electron/www
  • packaging       platform=linux arch=arm64 electron=4.0.1 appOutDir=platforms/electron/build/linux-arm64-unpacked
  • building        target=deb arch=arm64 file=platforms/electron/build/com.fooco.app_1.0.0_arm64.deb
  • downloading     parts=1 size=4.6 MB url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86/fpm-1.9.3-2.3.1-linux-x86.7
z
  • downloaded      duration=990ms url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86/fpm-1.9.3-2.3.1-linux-x86.7z
Error: Exit code: 1. Command failed: /home/ubuntu/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86/fpm -s dir -t deb --architecture arm64 --name com.fooco.app --force --
after-install /tmp/t-8X8reL/0-after-install --after-remove /tmp/t-8X8reL/1-after-remove --description
 The fooco App --version 1.0.0 --package /home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/platforms/electron/build/com.fooco.app_1.0.0_arm64.deb --m
aintainer fooco Team <jdoe@fooco.com> --url https://fooco.com --vendor fooco Team <jdoe@fooco.com> --deb-compression xz --depends gconf2 --depends gconf-service
 --depends libnotify4 --depends libappindicator1 --depends libxtst6 --depends libnss3 --depends libxss1 --license Apache-2.0 /home/ubuntu/fooco/fooappf3/fooapp-website/
fooapp-cordova/platforms/electron/build/linux-arm64-unpacked/=/opt/fooco App /home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/platforms/electron/buil
d-res/installer.png=/usr/share/icons/hicolor/0x0/apps/com.fooco.app.png /tmp/t-8X8reL/2-fooco App.desktop=/usr/share/applications/com.fooco.app.desktop
/home/ubuntu/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86/lib/ruby/bin/ruby: line 6: /home/ubuntu/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86/lib/ruby/bin.real
/ruby: cannot execute binary file: Exec format error
/home/ubuntu/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86/lib/ruby/bin/ruby: line 6: /home/ubuntu/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86/lib/ruby/bin.real
/ruby: Success

/home/ubuntu/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86/lib/ruby/bin/ruby: line 6: /home/ubuntu/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86/lib/ruby/bin.real
/ruby: cannot execute binary file: Exec format error
/home/ubuntu/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86/lib/ruby/bin/ruby: line 6: /home/ubuntu/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86/lib/ruby/bin.real
/ruby: Success
at /home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/node_modules/builder-util/src/util.ts:126:16
    at ChildProcess.exithandler (child_process.js:315:5)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
From previous event:
    at FpmTarget.build (/home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/node_modules/app-builder-lib/src/targets/fpm.ts:93:44)
    at /home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/node_modules/app-builder-lib/src/platformPackager.ts:131:24
From previous event:
    at AsyncTaskManager.add (/home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/node_modules/builder-util/src/asyncTaskManager.ts:14:20)
    at LinuxPackager.packageInDistributableFormat (/home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/node_modules/app-builder-lib/src/platformPackager.ts:123
:17)
    at /home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/node_modules/app-builder-lib/src/platformPackager.ts:114:10
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at LinuxPackager.pack (/home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at /home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16
    at callback (/home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/node_modules/graceful-fs/polyfills.js:299:20)
    at FSReqCallback.oncomplete (fs.js:184:5)
From previous event:
    at Packager.doBuild (/home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/node_modules/graceful-fs/graceful-fs.js:144:16
    at /usr/lib/node_modules/cordova/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (fs.js:171:23)
From previous event:
    at Packager._build (/home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Packager.build (/home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/node_modules/app-builder-lib/src/index.ts:59:28)
    at Object.build (/home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/node_modules/electron-builder/src/builder.ts:228:10)
    at ElectronBuilder.build (/home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/platforms/electron/cordova/lib/build.js:351:44)
    at /home/ubuntu/fooco/fooappf3/fooapp-website/fooapp-cordova/platforms/electron/cordova/lib/build.js:359:10
```

### Command or Code
`cordova build electron`

### Environment, Platform, Device
* ubuntu18 arm64
* electron platform, debian package artifact

### Version information
* cordova version 10.0.0 (via npm)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
Can you confirm if this is still a problem with Cordova Electron 3.0.0?

To upgrade:
```
cordova platform remove electron
cordova platform add electron@3.0.0
```

**Comment by bglowney** [comment]
yes it works as expected now, thank you!
